
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.65
blur = true

decorations = "Buttonless"

[font]
normal.family = "ComicShannsMono Nerd Font"

#regular
size = 24

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
